### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by minhasbushra** [jamesdgalbraith/TEstrainer#2]
I got the new TEstariner to work but after a few changes. 

1. On lines 165, 172, 184, i changes find ./{DATA_DIR} to find {DATA_DIR}

2. Also I observed the change in line 178 to           **if [ -f ${DATA_DIR}/trf/${RM_LIBRARY}.nonsatellite.classified ]; then**       from  
 if [ -f ${DATA_DIR}/trf/${RM_LIBRARY}.nonsatellite ]; then       in the old version. Using the old version, this part of the code works and Cdd is used to find proteins. Now with the new version cdd part don't work (i tried it with the same set of sequences). 

3. my repeat library contain 200 sequences, but the output new consensus file i am getting contain 204 sequences.  

4. On line 206, **if [ "$CLASSIFY" == TRUE ] && [ -s ${DATA_DIR}/chimeras/rinsed_${RM_LIBRARY}.nonsatellite] ; then**     there is space missing after nonsatellite. 

Thanks

**Comment by minhasbushra** [comment]
Also, one warning 

Making directories for run 1
Splitting run 1
Initial trf check for 1
sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
62% 125:75=0s ltr-1_family-216.fasta                                            sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
100% 200:0=0s ltr-1_family-279.fasta                                            
Initial blast and preparation for MSA 1
sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
0% 0:200=0s ltr-1_family-121.fasta                                              sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
0% 0:200=0s ltr-1_family-121.fasta                                              sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
7% 15:185=0s ltr-1_family-135.fasta                                             sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
8% 17:183=10s ltr-1_family-137.fasta                                            sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
13% 26:174=13s ltr-1_family-145.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
13% 26:174=19s ltr-1_family-145.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
19% 38:162=17s ltr-1_family-156.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
21% 43:157=18s ltr-1_family-17.fasta                                            sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
23% 47:153=19s ltr-1_family-164.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
24% 49:151=21s ltr-1_family-166.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
26% 52:148=21s ltr-1_family-169.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
28% 56:144=23s ltr-1_family-172.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
31% 63:137=21s ltr-1_family-179.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
35% 70:130=20s ltr-1_family-185.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
35% 71:129=20s ltr-1_family-186.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
39% 78:122=20s ltr-1_family-192.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
40% 80:120=20s ltr-1_family-194.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
41% 82:118=20s ltr-1_family-196.fasta                                           Whoa boy, ltr-1_family-19#DNA/hAT-Blackjack is inside tandem repeat
**/projects/***/scripts/TEstrainer-main/scripts/initial_mafft_setup.py:126: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  non_trf_seq=SeqRecord(seq=Seq(str(start_seq.seq)[int(non_trf_longest_df['Start']):int(non_trf_longest_df['End'])]),** id=start_seq.id, name=start_seq.name)
42% 85:115=20s ltr-1_family-199.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
45% 90:110=19s ltr-1_family-202.fasta                                           sh: /dev/tty: No such device or address

**Comment by minhasbushra** [comment]
Also, one warning 

Making directories for run 1
Splitting run 1
Initial trf check for 1
sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
62% 125:75=0s ltr-1_family-216.fasta                                            sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
100% 200:0=0s ltr-1_family-279.fasta                                            
Initial blast and preparation for MSA 1
sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
0% 0:200=0s ltr-1_family-121.fasta                                              sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
0% 0:200=0s ltr-1_family-121.fasta                                              sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
0% 0:200=0s ltr-1_family-121.fasta                                              sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
0% 0:200=0s ltr-1_family-121.fasta                                              sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
0% 0:200=0s ltr-1_family-121.fasta                                              sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
0% 0:200=0s ltr-1_family-121.fasta                                              sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
0% 0:200=0s ltr-1_family-121.fasta                                              sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
7% 15:185=0s ltr-1_family-135.fasta                                             sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
8% 17:183=10s ltr-1_family-137.fasta                                            sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
13% 26:174=13s ltr-1_family-145.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
13% 26:174=19s ltr-1_family-145.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
19% 38:162=17s ltr-1_family-156.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
21% 43:157=18s ltr-1_family-17.fasta                                            sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
23% 47:153=19s ltr-1_family-164.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
24% 49:151=21s ltr-1_family-166.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
26% 52:148=21s ltr-1_family-169.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
28% 56:144=23s ltr-1_family-172.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
31% 63:137=21s ltr-1_family-179.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
35% 70:130=20s ltr-1_family-185.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
35% 71:129=20s ltr-1_family-186.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
39% 78:122=20s ltr-1_family-192.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
40% 80:120=20s ltr-1_family-194.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
41% 82:118=20s ltr-1_family-196.fasta                                           Whoa boy, ltr-1_family-19#DNA/hAT-Blackjack is inside tandem repeat
**/projects/EARLGREY/EarlGrey/scripts/TEstrainer-main/scripts/initial_mafft_setup.py:126: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  non_trf_seq=SeqRecord(seq=Seq(str(start_seq.seq)[int(non_trf_longest_df['Start']):int(non_trf_longest_df['End'])]), id=start_seq.id, name=start_seq.name)**
42% 85:115=20s ltr-1_family-199.fasta                                           sh: /dev/tty: No such device or address
sh: /dev/tty: No such device or address
45% 90:110=19s ltr-1_family-202.fasta                                           sh: /dev/tty: No such device or address

**Comment by jamesdgalbraith** [comment]
Thanks for bringing these issues up, I've fixed the path issues and line 206 statement. The FutureWarning flagged shouldn't impact your out data as that's due to a change that will be coming in a future version of  pandas. I'll look into the number of sequences increasing and see if I can replicate with any of my datasets.

**Comment by minhasbushra** [comment]
Thanks, so I figured we have multiple sequences of some TEs with different classifications. Like >ltr-1_family-148#LTR/Unknown as the original fasta header and another as  >ltr-1_family-148#Satellite.
